#!/bin/bash

echo "Running custom docker commands"

docker rm $(docker ps -aq)

docker volume rm project_keyshare

docker volume rm project_blocks

docker volume rm project_node

# docker build -f transfer_python/Dockerfile -t harsh/transfer:v1 .

docker build -f djangodocker -t harsh/djangoapp:v1 .

echo "Done Shit!"
